const express = require('express')
const body_parser = require('body-parser')
const cors = require('cors')
const database = require('./db')
const router = require('./routes') 
const app = express()
app.use(body_parser.urlencoded({extended:true}))
app.use(cors())
app.use(body_parser.json())
database.on('error',console.error.bind(console,'database connection error'))
app.get('/',(req,res)=>{
    res.send('server is running')
})
app.use('/api',router)
app.listen(8080,()=>console.log('server is running at 8080 port'))